name: daily super bot
on:
    push:
env:
    Telegram_token: ${{secrets.TELEGRAM_TOKEN }}
    telegam_channel_id: ${{secrets.TELEGAM_CHANNEL_ID }}
jobs:
   Daily-Run:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
       - name: Install Dependensies
         run: pip install -r requirements.txt
       - name: Run App
         run: python app.py
